name: Release & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Release new version
        id: release
        uses: ridedott/release-me-action@v3.10.7
        with:
          release-branches: '["main"]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Get new version
        run: echo "VERSION=${{ steps.release.outputs.version }}" >> $GITHUB_ENV

      - name: Create version.json
        run: |
          echo '{
            "version": "'${VERSION}'",
            "build_date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
            "description": "Test versioning for S3 static site"
          }' > version

      - name: Sync all files to S3
        run: aws s3 sync . s3://test-versioning-buckets --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
